# -*- coding: utf-8 -*-
"""code.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12KJTjXOe_HqRlaVg5EOzqsGxaYNMQfgJ
"""

import pandas as pd
import numpy as np

df = pd.read_csv(r"C:\Users\user\Downloads\adult.csv~1\adult.csv")
df.head()
df.tail()
print(df.shape)
print(df.columns)

df.head()

df.info()
df.describe()
df.nunique()

df.isnull().sum()

df.replace('?', np.nan, inplace=True)

df.drop_duplicates(inplace=True)

num_cols = df.select_dtypes(include=['int64', 'float64']).columns
cat_cols = df.select_dtypes(include=['object']).columns


for col in num_cols:

    df[col].fillna(df[col].mean(), inplace=True)


for col in cat_cols:
    df[col].fillna(df[col].mode()[0], inplace=True)

print(df.isnull().sum())

df.to_csv("cleaned_adult.csv", index=False)

df.duplicated()

df.duplicated().sum()

df.drop_duplicates(inplace=True)

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

data = pd.read_csv("cleaned_adult.csv")
data.columns = data.columns.str.strip()
data['income'] = data['income'].str.strip()

continuous_cols = ['education.num', 'hours.per.week', 'capital.gain', 'capital.loss']
categorical_cols = ['sex', 'workclass', 'education']

plt.figure(figsize=(16,4))
for i, col in enumerate(continuous_cols[:3]):
    plt.subplot(1,3,i+1)
    sns.histplot(data=data, x=col, kde=True, color='skyblue')
    plt.title(f'Distribution of {col}')
plt.tight_layout()
plt.show()

plt.figure(figsize=(16,4))
for i, col in enumerate(continuous_cols[:3]):
    plt.subplot(1,3,i+1)
    sns.boxplot(data=data, x='income', y=col, palette='Set2')
    plt.title(f'{col} vs Income')
plt.tight_layout()
plt.show()

plt.figure(figsize=(16,4))
for i, col in enumerate(categorical_cols):
    plt.subplot(1,3,i+1)
    if data[col].nunique() > 6:
        sns.countplot(data=data, y=col, order=data[col].value_counts().index, palette='Set3')
    else:
        sns.countplot(data=data, x=col, palette='Set3')
    plt.title(f'Counts of {col}')
plt.tight_layout()
plt.show()

plt.figure(figsize=(6,5))
sns.heatmap(data[continuous_cols].corr(), annot=True, cmap='coolwarm', fmt=".2f")
plt.title("Correlation Heatmap")
plt.show()

plt.figure(figsize=(16,4))
for i, col in enumerate(categorical_cols):
    plt.subplot(1,3,i+1)
    if data[col].nunique() > 6:
        sns.histplot(data=data, y=col, hue='income', multiple='stack', palette='Set2')
    else:
        sns.countplot(data=data, x='income', hue=col, palette='Set2')
    plt.title(f'{col} vs Income')
plt.tight_layout()
plt.show()