# -*- coding: utf-8 -*-
"""App.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1d24Yaws37AdO-tyyXExI1vQOoNq6th-z
"""

import pandas as pd

df = pd.read_csv(r"E:\Study\DEPI DS 20-26\Technical\DA\SuperStoreOrders - SuperStoreOrders.csv")

print(df.head())
print(df.info())
print(df.describe())
print(df.shape)
print(df.columns)
print(df.dtypes)

df['order_date'] = pd.to_datetime(df['order_date'], dayfirst=True)
df['ship_date'] = pd.to_datetime(df['ship_date'], dayfirst=True)

df['sales'] = pd.to_numeric(df['sales'].str.replace(',', ''))

df['shipping_days'] = (df['ship_date'] - df['order_date']).dt.days
df['month'] = df['order_date'].dt.month
df['year'] = df['order_date'].dt.year

df.dtypes

df['profit_margin'] = df['profit'] / df['sales']
df['unit_price'] = df['sales'] / df['quantity']
df['category'] = df['category'].str.strip()

df.head()

df.isnull().sum()

df.duplicated().sum()

df.nunique()

df_encoded = pd.get_dummies(
    df,
    columns=[
        'ship_mode',
        'segment',
        'market',
        'region',
        'category',
        'sub_category',
        'order_priority'
    ],
    drop_first=True
)
df_encoded

df_reduced= df.groupby('category')['sales'].sum().sort_values(ascending=False)
df_reduced.head()

import seaborn as sns
sns.boxplot(x=df['profit'])

Q1 = df['profit'].quantile(0.25)
Q3 = df['profit'].quantile(0.75)

IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

outliers = df[(df['profit'] < lower) | (df['profit'] > upper)]

print(len(outliers))

df_clean = df[(df['profit'] >= lower) & (df['profit'] <= upper)]
print(df_clean)