# -*- coding: utf-8 -*-
"""Burnout_level.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VNYkL1ys68etTlKETgPAAjbYxAl_ndZe
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

df1 = pd.read_csv('/content/student_mental_health_burnout 2.csv')
df2 = pd.read_csv('/content/student_mental_health_burnout.csv')

print(f"Dataset 1: {df1.shape}")
print(f"Dataset 2: {df2.shape}")

df1.info()

df2.info()

df1.columns = [col.lower().strip().replace(' ', '_') for col in df1.columns]
df2.columns = [col.lower().strip().replace(' ', '_') for col in df2.columns]

df1['source'] = 'batch_1'
df2['source'] = 'batch_2'

df_combined = pd.concat([df1, df2], axis=0, ignore_index=True)

df_combined['age'] = pd.to_numeric(df_combined['age'], errors='coerce')

df_combined.drop_duplicates(inplace=True)

df_combined = df_combined.applymap(lambda x: x.strip() if isinstance(x, str) else x) #spacesss

if 'burnout_score' in df_combined.columns:
    median_score = df_combined['burnout_score'].median()
    df_combined['burnout_score'].fillna(median_score, inplace=True) #median to fill extra spaceszz

df_combined.to_csv('cleaned_student_burnout.csv', index=False)
print("Data cleaned and saved!")

"""BURNOUT_LEVEL"""

df_combined['burnout_level'] = df_combined['burnout_level'].str.strip().str.capitalize() #standardlizes text and fixes capitals and stuff

print(df_combined['burnout_level'].unique()) #aany unique wrds

mode_val = df_combined['burnout_level'].mode()[0] #most frequent value in clms
df_combined['burnout_level'].fillna(mode_val, inplace=True)

sns.countplot(data=df_combined, x='burnout_level', palette='viridis')
plt.title('Count of Students by Burnout Level')
plt.show() #bars even = data balance

print(df_combined.columns.tolist())

sns.boxplot(data=df_combined, x='burnout_level', y='daily_sleep_hours') ##Damount of sleep a student gets correlate with their burnout level?
plt.title('Sleep Hours vs Burnout Level')
plt.show()

sns.boxplot(data=df_combined, x='burnout_level', y='stress_level')
plt.title('Stress vs Sleep')
plt.show()

sns.boxplot(data=df_combined, x='burnout_level', y='daily_study_hours')
plt.title('Study Hours vs Burnout')
plt.show()

print(df_combined.groupby('burnout_level')['daily_sleep_hours'].describe())

plt.figure(figsize=(10,6))
sns.kdeplot(data=df_combined, x='daily_sleep_hours', hue='burnout_level', fill=True)
plt.title('Overlap of Sleep Hours by Burnout Level')
plt.show()