# -*- coding: utf-8 -*-
"""Car_.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1glgxxt4TaOrnNAoBGIwgeJ00yuD5opwP
"""

import pandas as pd
import numpy as np

df = pd.read_csv('bmw_cars_market_dataset_synthetic.csv')

df.size

df.shape[0]

df.shape[1]

df.dtypes

df.info()

if 'car_id' in df.columns:
    df.drop(columns=['car_id'], inplace=True)

df.info()

df.columns = (
    df.columns
    .str.strip()
    .str.lower()
    .str.replace(' ', '_')
    .str.replace('.', '_')
)

df.columns.tolist()

transmission_mode = df['transmission'].mode()[0]
df['transmission'] = df['transmission'].fillna(transmission_mode)

fuel_median = df['fuel_consumption_l_per_100km'].median()
df['fuel_consumption_l_per_100km'] = df['fuel_consumption_l_per_100km'].fillna(fuel_median)

df['service_history'] = df['service_history'].fillna('unknown')

int_cols = ['year', 'horsepower', 'mileage_km', 'co2_emissions_g_km', 'owner_count']
float_cols = ['engine_size', 'fuel_consumption_l_per_100km', 'price_usd']

for col in int_cols:
    df[col] = pd.to_numeric(df[col], errors='coerce').fillna(0).astype(int)

for col in float_cols:
    df[col] = pd.to_numeric(df[col], errors='coerce').astype(float)

cat_cols = [
    'model', 'fuel_type', 'transmission', 'drivetrain',
    'body_type', 'color', 'accident_history',
    'service_history', 'country_sold'
]

for col in cat_cols:
    df[col] = df[col].astype('category')

mapping = {
    'fuel_type': {'petrol': 'petrol', 'petrol ': 'petrol', 'diesel': 'diesel', 'electric': 'electric'},
    'transmission': {'auto': 'automatic', 'aut': 'automatic', 'man': 'manual'}
}

for col, replace_map in mapping.items():
    if col in df.columns:
        df[col] = df[col].str.lower().str.strip().replace(replace_map)

cols_to_fix = ['engine_size', 'horsepower', 'mileage_km', 'price_usd', 'fuel_consumption_l_per_100km']

for col in cols_to_fix:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    df[col] = df[col].clip(lower=lower_bound, upper=upper_bound)

"""### Feature Engineering"""

import datetime
current_year = 2025

df['car_age'] = current_year - df['year']

df['price_per_hp'] = df['price_usd'] / df['horsepower']

df['mileage_per_year'] = df['mileage_km'] / df['car_age'].replace(0, 1)

df['engine_efficiency'] = df['horsepower'] / df['engine_size']

df['accident_history_enc'] = df['accident_history'].map({'no': 0, 'yes': 1}).fillna(0)

service_map = {'full': 2, 'partial': 1, 'unknown': 0}
df['service_history_enc'] = df['service_history'].map(service_map).fillna(0)



def categorize_fuel(cons):
    if cons < 6: return 'efficient'
    elif 6 <= cons <= 9: return 'moderate'
    else: return 'inefficient'

df['fuel_efficiency_cat'] = df['fuel_consumption_l_per_100km'].apply(categorize_fuel)

luxury_list = ['5 Series', '7 Series', 'X5', 'X7', 'M5', 'M8']
df['luxury_model'] = df['model'].apply(lambda x: 1 if any(lux in str(x) for lux in luxury_list) else 0)

target_cols = [
    'price_usd',
    'mileage_km',
    'horsepower',
    'engine_size',
    'fuel_consumption_l_per_100km'
]

stats = df[target_cols].describe().T

summary = stats[['mean', '50%', 'min', 'max', 'std']]
summary.rename(columns={'50%': 'median'}, inplace=True)

print("\n--- Summary Statistics ---")
print(summary)